annotations:
  commit: 179b8e72fbc4f916dda03ab4d7e61e5141cf2248
  created: "2026-01-07T17:45:12+00:00"
  dpfVersion: v25.10.1
apiVersion: v2
appVersion: v25.10.1
dependencies:
- condition: ovn-kubernetes-resource-injector.enabled
  name: ovn-kubernetes-resource-injector
  repository: ""
  version: 1.0.0
description: Helm chart to deploy ovn-kubernetes in the NVIDIA DOCA Platform Framework
  (DPF) context
home: https://ovn-kubernetes.io/
icon: https://www.ovn.org/images/ovn-logo.png
name: ovn-kubernetes-chart
sources:
- https://github.com/ovn-org/ovn-kubernetes
- https://github.com/ovn-org/ovn
type: application
version: v25.10.1
