{{- if and (eq .Values.license.type "enterprise") .Values.license.enterprise.activateLicense }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: px-activate-license
  namespace: {{ .Values.storageCluster.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: px-activate-license-role
  namespace: {{ .Values.storageCluster.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: px-activate-license-rolebinding
  namespace: {{ .Values.storageCluster.namespace }}
subjects:
  - kind: ServiceAccount
    name: px-activate-license
roleRef:
  kind: Role
  name: px-activate-license-role
  apiGroup: rbac.authorization.k8s.io     
---
apiVersion: batch/v1
kind: Job
metadata:
  name: px-activate-license
  namespace: {{ .Values.storageCluster.namespace }}
spec:
  template:
    metadata:
      name: px-activate-license
    spec:
      serviceAccountName: px-activate-license
      initContainers:
        - name: init-px-activate-license
          image: bitnamilegacy/kubectl:latest
          command: ['sh', '-c', "until kubectl wait --for=condition=ready pod -l name=portworx -n {{ .Values.storageCluster.namespace }} --timeout=1m; do echo Waiting for portworx; sleep 120; done"]
      containers:
        - name: kubectl-pod
          image: bitnamilegacy/kubectl:latest
          command:
            - "bash"
            - "-c"
            - {{ template "portworx-generic.setPxEnterpriseLicense" . }}
      restartPolicy: Never
{{- end }}